# Generated by Django 5.1.4 on 2026-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Form Status',
            },
        ),
        migrations.CreateModel(
            name='Form_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('participant', 'General Participant / Delegate'), ('competition', 'Competition')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('eee', 'Electrical & Electronic Engineering'), ('mech_civil', 'Mechanical / Civil Engineering'), ('bba_econ', 'Business Administration / Economics'), ('env_policy', 'Environmental Science & Policy'), ('cs', 'Computer Science'), ('other', 'Other')], max_length=20)),
                ('student_id', models.CharField(max_length=50)),
                ('study_level', models.CharField(choices=[('undergrad', 'Undergraduate Student'), ('grad', "Graduate / Master's Student"), ('fresh_grad', 'Fresh Graduate'), ('faculty', 'Faculty / Academician'), ('industry', 'Industry Professional')], max_length=20)),
                ('ambassador_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('ieee', 'IEEE Member'), ('non_ieee', 'Non-IEEE Member')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ieee_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_members', models.CharField(blank=True, choices=[('1', 'Solo (1 Member)'), ('2', '2 Members'), ('3', '3 Members')], max_length=5, null=True)),
                ('mem2_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem2_university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem2_department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem2_student_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mem2_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('mem2_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mem3_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem3_university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem3_department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mem3_student_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mem3_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('mem3_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('track', models.CharField(blank=True, choices=[('track_a', 'Track A: Grid Modernization, Smart Grids & Load-Shedding Mitigation'), ('track_b', 'Track B: Renewable Integration, Energy Storage & Decarbonization'), ('track_c', 'Track C: Energy Policy, FDI Frameworks & Market Restructuring')], max_length=20, null=True)),
                ('project_title', models.CharField(blank=True, max_length=300, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('proposed_solution', models.TextField(blank=True, null=True)),
                ('sdg_alignment', models.JSONField(blank=True, default=list)),
                ('abstract_file', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Participant',
            },
        ),
    ]
