# Generated by Django 5.1.4 on 2026-10-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_participant_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_participant',
            name='comp_transaction_id',
        ),
    ]
