# Generated by Django 5.1.4 on 2026-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_competition_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant',
            name='track',
            field=models.CharField(blank=True, choices=[('track_a', 'Track A: Irrigation, Community Village, EV Charging'), ('track_b', 'Track B: Urban Community, Carbon Capture Modelling, Economically Feasible')], max_length=20, null=True),
        ),
    ]
