# Generated by Django 5.1.4 on 2026-10-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_update_track_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_participant',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
