# Generated by Django 5.1.4 on 2026-10-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventformstatus',
            options={'verbose_name': 'Form status', 'verbose_name_plural': 'Form status'},
        ),
    ]
