# Generated by Django 5.1.4 on 2026-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_form_status_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
